apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  minReplicas: 2        # Минимум подов ночью + отказоустойчивость
  maxReplicas: 4        # Максимум — по пиковым нагрузкам
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150 # Скейлимся при 150% загрузке CPU (150m)