apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-app-pdb
spec:
  minAvailable: 1 # Всегда должно быть доступно минимум 1 под
  selector:
    matchLabels:
      app: web-app